##Presentations 
##Admissions
#Required packages
library(ggplot2, lib.loc = "C:/Program Files/R/R-4.0.1/library")
library(tidyverse, lib.loc = "C:/Program Files/R/R-4.0.1/library")
library(haven)
library(expsmooth, lib.loc = "C:/Program Files/R/R-4.0.1/library") 

#The following packages may be necessary.
library(timeDate, lib.loc = "C:/Program Files/R/R-4.0.1/library")
library(tseries, lib.loc = "C:/Program Files/R/R-4.0.1/library")
library(zoo, lib.loc = "C:/Program Files/R/R-4.0.1/library")
library(xts, lib.loc = "C:/Program Files/R/R-4.0.1/library")
library(fracdiff, lib.loc = "C:/Program Files/R/R-4.0.1/library") 
library(lmtest, lib.loc = "C:/Program Files/R/R-4.0.1/library")
library(rpart, lib.loc = "C:/Program Files/R/R-4.0.1/library")
library(splines, lib.loc = "C:/Program Files/R/R-4.0.1/library")
library(boot, lib.loc = "C:/Program Files/R/R-4.0.1/library")
library(dplyr, lib.loc = "C:/Program Files/R/R-4.0.1/library")

#Import ARIMA dataset
library(readxl)
ARIMA <- read_excel("//hscni.net/bso/Honest Broker Service/Project 060/ENPaterson files/Datasets/Datasets generated by ENP/ARIMA.xlsx")

#Format ARIMA Dataset
str(ARIMA)

##ARIMA for presentations

#Visualise monthly variation with bar charts
ARIMA  %>% 
  filter(c_month %in% c(1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12)) %>%
  ggplot(aes(x=as.factor(year), y=SI_admissions_n))+
  geom_bar(stat="identity")+
  facet_wrap(~c_month)+
  labs(
    x = "Month",
    y = "Presentations (n)"
  )+
  theme(axis.text.x = element_text(angle = 90))

#Visualise monthly variation with a line graph
ARIMA %>% 
  ggplot(aes(x=month, y=SI_admissions_n))+
  geom_line()+
  labs(
    y = "Presentations (n)"
  )

#Visualise monthly variation with annual line graph
ARIMA  %>% 
  filter(year %in% c(2012, 2013, 2014, 2015, 2016, 2017, 2018, 2019, 2020)) %>%
  ggplot(aes(x=c_month, y=SI_admissions_n))+
  geom_line()+
  facet_wrap(~year)+
  labs(
    x = "Month",
    y = "Presentations (n)"
  )+
  theme(axis.text.x = element_text(angle = 90))

##Split Dataset into PRE and POST COVID 
#This creates values subheadings in the "environment" window of r studio relating to the specified data.

# PRECOVID Apr 2012 to Dec 2019
# sh_month 4 - 96 (from rows 1-93)
ARIMA_2012_2019 <- ARIMA$SI_admissions_n[1:93]      

# POSTCOVID Jan 2020 to Sep 2020
# sh_month 4 - 96 (from rows 94-102)
ARIMA_2020 <- ARIMA$SI_admissions_n[94:102]   

#Datasets created in STATA
#Create time series for precovid data
#This syntax only works after the preceding steps have been performed.
ARIMA_2012_2019_ts <- ts(ARIMA_2012_2019, 
                         start=c(2012,4),  #first in time series is Apr 2012
                         end=c(2019,12),    #last in time series is Dec 2019
                         freq=12)          #i.e. monthly data

#Plot of monthly individuals over the precovid time frame
autoplot(ARIMA_2012_2019_ts) +   ylab("Presentations (n)")

#Take first difference in data to remove upward trend
diff_ARIMA_2012_2019 <- diff(ARIMA_2012_2019_ts)

#Plot the differenced values (i.e. the month to month differences)
autoplot(diff_ARIMA_2012_2019) +   ylab("Presentations (n)")

##Check for seasonality in stationary data set (i.e. the differenced data)
ggseasonplot(diff_ARIMA_2012_2019) +   ylab("Presentations (n)")

#Alternative view of seasonal variation
ggsubseriesplot(diff_ARIMA_2012_2019) +   ylab("Presentations (n)")

#1. Benchmark method: Seasonal naive model 
#i.e. Each month's value is equal to the next +/- random error
# Use differenced data (i.e. the un-trended data, "diff_freq")
set.seed(123)
fit_naive_ARIMA_2012_2019 <-snaive(diff_ARIMA_2012_2019)  
summary(fit_naive_ARIMA_2012_2019)

checkresiduals(fit_naive_ARIMA_2012_2019)

#improvement over Naive method in terms of errors outside of 95%CI 

set.seed(123)
fit_ets_ARIMA_2012_2019<- ets(ARIMA_2012_2019_ts)
# ets() tries many ETS (Error, Trend, Seasonal) models and chooses the best performing
# use the actual (not differenced) data, as it can use trends
summary(fit_ets_ARIMA_2012_2019)
checkresiduals(fit_ets_ARIMA_2012_2019)

#3. ARIMA model
set.seed(123)
fit_arima_ARIMA_2012_2019 <- auto.arima(ARIMA_2012_2019_ts,       
                                        d=1,               # d1 to take first difference of data to remove trend
                                        D=1,               # D1 to take the first seasonal difference to remove seasonal trends
                                        stepwise = F,      # if true, the algorithm would try a smaller number to save time (costs accuracy)
                                        approximation = F, # if true, the AIC would be an approximation to save time (costs accuracy)
                                        trace = T          # prints models as they run
)


#Check performance of ARIMA on the precovid data
summary(fit_arima_ARIMA_2012_2019)
checkresiduals(fit_arima_ARIMA_2012_2019)


#Use the ARIMA model to forecast data into POSTCOVID timeframe
forecast_arima_ARIMA_2012_2019 <- forecast(fit_arima_ARIMA_2012_2019,
                                           h=9) # forecast 9 months (Jan 2020 to Sep 2020)
autoplot(forecast_arima_ARIMA_2012_2019) # additional argument include = 12, would include only the last 12 months in precovid time frame

#Return forecast and upper/lower confidence intervals
summary(forecast_arima_ARIMA_2012_2019)

#Extract the forecast values with the upper and lower 80 and 95% CI limits, and view the actual values for the POSTCOVID time frame
forecast_arima_ARIMA_2012_2019_df <- data.frame(forecast_arima_ARIMA_2012_2019$mean)
lower_ARIMA_2012_2019_df <- as.data.frame(forecast_arima_ARIMA_2012_2019$lower,row.names = FALSE)
upper_ARIMA_2012_2019_df <- as.data.frame(forecast_arima_ARIMA_2012_2019$upper,row.names = FALSE)
ARIMA_2020_df <- as.data.frame(ARIMA_2020)
forecast_arima_ARIMA_2012_2019_df 

lower_ARIMA_2012_2019_df

upper_ARIMA_2012_2019_df

ARIMA_2020_df

#Pull the values from forecast and actual values together in a data frame
forecast_arima_ARIMA_2012_2019_df <- cbind(forecast_arima_ARIMA_2012_2019_df, lower_ARIMA_2012_2019_df, upper_ARIMA_2012_2019_df, ARIMA_2020_df)

column_names <-  c("mean", "lower80", "lower95", "upper80", "upper95", "actual")

colnames(forecast_arima_ARIMA_2012_2019_df) <- column_names

month <- c("Jan", "Feb", "Mar", "Apr", "May", "Jun", "Jul", "Aug", "Sep")
forecast_arima_ARIMA_2012_2019_df <- forecast_arima_ARIMA_2012_2019_df %>%
  add_column(month, .before = "mean")

forecast_arima_ARIMA_2012_2019_df$month <- factor(forecast_arima_ARIMA_2012_2019_df$month, levels = c("Jan", "Feb", "Mar", "Apr", "May", "Jun", "Jul", "Aug", "Sep"))

forecast_arima_ARIMA_2012_2019_df

#Visualise the forecast (with confidence intervals) versus the individuals in the POSTCOVID timeframe
ggplot(data = forecast_arima_ARIMA_2012_2019_df,
       aes(x= forecast_arima_ARIMA_2012_2019_df$month, y=mean, group=1))+
  geom_point()+
  geom_line()+
  geom_ribbon(aes(ymin= forecast_arima_ARIMA_2012_2019_df$lower95, ymax= forecast_arima_ARIMA_2012_2019_df$upper95), linetype=2, alpha=0.1)+
  geom_ribbon(aes(ymin= forecast_arima_ARIMA_2012_2019_df$lower80, ymax= forecast_arima_ARIMA_2012_2019_df$upper80), linetype=2, alpha=0.2)+
  geom_point(aes(x= forecast_arima_ARIMA_2012_2019_df$month, y= forecast_arima_ARIMA_2012_2019_df$actual, group=1, col="red"))+
  geom_line(aes(x= forecast_arima_ARIMA_2012_2019_df$month, y= forecast_arima_ARIMA_2012_2019_df$actual, group=1, col="red"))+
  labs(
    caption = paste("Black = forecast values\nRed = actual values\nDark grey band = 80% confidence interval\nLight grey band = 95% confidence interval"),     x = "Month",
    y = "Presentations (n)"
  )+
  theme_minimal()+
  theme(legend.position = "none") +  
  ylim(0, 1500)
ggsave("Rplot12.pdf", width = 10, height = 10, units = c("cm"))
ggsave("Rplot12_large.pdf", width = 15, height = 15, units = c("cm"))

