#Required packages
library(ggplot2)
library(tidyverse)
library(haven)
library(expsmooth)
library(tibble)
library(tidyr)
library(stringr)


#The following packages may be necessary.
library(timeDate)
library(tseries)
library(zoo)
library(xts)
library(fracdiff) 
library(lmtest)
library(rpart)
library(splines)
library(boot)
library(dplyr)

#Import ARIMA dataset
library(readxl)
ARIMA <- read_excel("//hscni.net/bso/Honest Broker Service/Project 060/ENPaterson files/Datasets/Datasets generated by ENP/ARIMA.xlsx")

#Format ARIMA Dataset
str(ARIMA)

##ARIMA for rate of individuals presenting

#Visualise monthly variation

#Visualise monthly variation with bar charts
ARIMA  %>% 
  filter(c_month %in% c(1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12)) %>%
  ggplot(aes(x=as.factor(year), y=admitted_n_1624))+
  geom_bar(stat="identity")+
  facet_wrap(~c_month)+
  labs(
    x = "Month",
    y = "Individuals Presenting (n)"
  )+
  theme(axis.text.x = element_text(angle = 90))

#Visualise monthly variation with a line graph
ARIMA %>% 
  ggplot(aes(x=month, y=admitted_n_1624))+
  geom_line()+
  labs(
    y = "Individuals Presenting (n)"
  )

#Visualise monthly variation with annual line graph
ARIMA  %>% 
  filter(year %in% c(2012, 2013, 2014, 2015, 2016, 2017, 2018, 2019, 2020)) %>%
  ggplot(aes(x=c_month, y=admitted_n_1624))+
  geom_line()+
  facet_wrap(~year)+
  labs(
    x = "Month",
    y = "Individuals Presenting (n)"
  )+
  theme(axis.text.x = element_text(angle = 90))

# PRECOVID Apr 2012 to Feb 2020
# sh_month 4 - 98 (i.e. March to September, found in rows 1-95 of the R-studio ARIMA dataset created above)
ARIMA_2012_2019 <- ARIMA$admitted_n_1624[1:95]      

# POSTCOVID Mar 2020 to Sep 2020
# sh_month 99 - 105 (i.e. March to September, found in from rows 96-102 of the R-studio ARIMA dataset created above)
ARIMA_2020 <- ARIMA$admitted_n_1624[96:102]   

#Datasets created in STATA
#Create time series for precovid data
#This syntax only works after the preceding steps have been performed.
ARIMA_2012_2019_ts <- ts(ARIMA_2012_2019, 
                         start=c(2012,4),  #first in time series is Apr 2012
                         end=c(2020,2),    #last in time series is Feb 2020
                         freq=12)          #i.e. monthly data

#Plot of monthly individuals over the precovid time frame
autoplot(ARIMA_2012_2019_ts) +  ylab("Individuals Presenting (n)")

#Take first difference in data to remove upward trend
diff_ARIMA_2012_2019 <- diff(ARIMA_2012_2019_ts)

#Plot the differenced values (i.e. the month to month differences)
autoplot(diff_ARIMA_2012_2019) +
  ylab("Individuals Presenting (n)")

##Check for seasonality in stationary data set (i.e. the differenced data)
ggseasonplot(diff_ARIMA_2012_2019) + ylab("Individuals Presenting (n)")

#Alternative view of seasonal variation
ggsubseriesplot(diff_ARIMA_2012_2019) +  ylab("Individuals Presenting (n)")

#1. Benchmark method: Seasonal naive model 
#i.e. Each month's value is equal to the next +/- random error
# Use differenced data (i.e. the un-trended data, "diff_freq")
set.seed(123)
fit_naive_ARIMA_2012_2019 <-snaive(diff_ARIMA_2012_2019)  
summary(fit_naive_ARIMA_2012_2019)

checkresiduals(fit_naive_ARIMA_2012_2019)

#improvement over Naive method in terms of errors outside of 95%CI 

set.seed(123)
fit_ets_ARIMA_2012_2019<- ets(ARIMA_2012_2019_ts)
# ets() tries many ETS (Error, Trend, Seasonal) models and chooses the best performing
# use the actual (not differenced) data, as it can use trends
summary(fit_ets_ARIMA_2012_2019)
checkresiduals(fit_ets_ARIMA_2012_2019)

#3. ARIMA model
set.seed(123)
fit_arima_ARIMA_2012_2019 <- auto.arima(ARIMA_2012_2019_ts,       
                                        d=1,               # d1 to take first difference of data to remove trend
                                        D=1,               # D1 to take the first seasonal difference to remove seasonal trends
                                        stepwise = F,      # if true, the algorithm would try a smaller number to save time (costs accuracy)
                                        approximation = F, # if true, the AIC would be an approximation to save time (costs accuracy)
                                        trace = T          # prints models as they run
)


#Check performance of ARIMA on the precovid data
summary(fit_arima_ARIMA_2012_2019)
checkresiduals(fit_arima_ARIMA_2012_2019)


#Use the ARIMA model to forecast data into POSTCOVID timeframe
forecast_arima_ARIMA_2012_2019 <- forecast(fit_arima_ARIMA_2012_2019,
                                           h=7) # forecast 7 months (Mar 2020 to Sep 2020)
autoplot(forecast_arima_ARIMA_2012_2019) # additional argument include = 12, would include only the last 12 months in precovid time frame

#Return forecast and upper/lower confidence intervals
summary(forecast_arima_ARIMA_2012_2019)

#Extract the forecast values with the upper and lower 80 and 95% CI limits, and view the actual values for the POSTCOVID time frame
forecast_arima_ARIMA_2012_2019_df <- data.frame(forecast_arima_ARIMA_2012_2019$mean)
lower_ARIMA_2012_2019_df <- as.data.frame(forecast_arima_ARIMA_2012_2019$lower,row.names = FALSE)
upper_ARIMA_2012_2019_df <- as.data.frame(forecast_arima_ARIMA_2012_2019$upper,row.names = FALSE)
ARIMA_2020_df <- as.data.frame(ARIMA_2020)
forecast_arima_ARIMA_2012_2019_df 

lower_ARIMA_2012_2019_df

upper_ARIMA_2012_2019_df

ARIMA_2020_df

#Pull the values from forecast and actual values together in a data frame
forecast_arima_ARIMA_2012_2019_df <- cbind(forecast_arima_ARIMA_2012_2019_df, lower_ARIMA_2012_2019_df, upper_ARIMA_2012_2019_df, ARIMA_2020_df)

column_names <-  c("mean", "lower80", "lower95", "upper80", "upper95", "actual")

colnames(forecast_arima_ARIMA_2012_2019_df) <- column_names

month <- c("Mar", "Apr", "May", "Jun", "Jul", "Aug", "Sep")
forecast_arima_ARIMA_2012_2019_df <- forecast_arima_ARIMA_2012_2019_df %>%
  add_column(month, .before = "mean")

forecast_arima_ARIMA_2012_2019_df$month <- factor(forecast_arima_ARIMA_2012_2019_df$month, levels = c("Mar", "Apr", "May", "Jun", "Jul", "Aug", "Sep"))

forecast_arima_ARIMA_2012_2019_df

#Visualise the forecast (with confidence intervals) versus the individuals in the POSTCOVID timeframe
ggplot(data = forecast_arima_ARIMA_2012_2019_df,
       aes(x= month, y=mean, group=1))+
  geom_point()+
  geom_line()+
  geom_ribbon(aes(ymin= lower95, ymax= upper95), linetype=2, alpha=0.1)+
  geom_ribbon(aes(ymin= lower80, ymax= upper80), linetype=2, alpha=0.2)+
  geom_point(aes(x= month, y= actual, group=1, col="red"))+
  geom_line(aes(x= month, y= actual, group=1, col="red"))+
  labs(
    caption = paste("Black = forecast values\nRed = actual values\nDark grey band = 80% confidence interval\nLight grey band = 95% confidence interval"),    x = "Month",
    y = "Individuals Presenting (n)"
  )+
  theme_minimal()+
  theme(legend.position = "none") +  
  
  ylim(0,500)
ggsave("Rplot12.pdf", width = 10, height = 10, units = c("cm"))
ggsave("Rplot12_large.pdf", width = 15, height = 15, units = c("cm"))